# Generated by Django 5.2.4 on 2025-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, help_text='Direct link to event page (e.g. Eventbrite, Zoom, Google Form)', null=True)),
            ],
        ),
    ]
