# Generated by Django 5.2.4 on 2025-11-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(default='Calendar', max_length=50),
        ),
    ]
