# Generated by Django 5.2.4 on 2025-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
