# Generated by Django 5.2.4 on 2026-01-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference'), ('symposium', 'Symposium'), ('book', 'Book'), ('patent', 'Patent')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(default=list)),
                ('info', models.CharField(max_length=255)),
                ('doi_url', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='universities.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=200)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='universities.researcher')),
            ],
        ),
    ]
