# Generated by Django 5.2.4 on 2026-01-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='researcher',
        ),
        migrations.DeleteModel(
            name='AcademicPlatform',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
