# Generated by Django 5.2.4 on 2026-01-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_remove_publication_researcher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio / CV / Resume')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='research_pictures/', verbose_name='Bio Picture (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_profile', related_query_name='research_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Profile',
                'verbose_name_plural': 'Research Profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('symposium', 'Symposium Presentation'), ('book', 'Book / Monograph'), ('patent', 'Patent')], default='journal', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('info', models.CharField(blank=True, help_text='Journal · Volume · Pages | Conference name & year | Publisher', max_length=500)),
                ('doi_url', models.URLField(blank=True, null=True, verbose_name='DOI or URL')),
                ('abstract', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publications/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='universities.researchprofile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(help_text='e.g. ORCID: 0000-0002-1825-0097, Scopus ID: 12345678900', max_length=200, verbose_name='Platform ID')),
                ('research_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_platforms', to='universities.researchprofile')),
            ],
            options={
                'ordering': ['platform_id'],
            },
        ),
    ]
