# Generated by Django 5.2.4 on 2026-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-status_changed_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Last Changed'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', 'research_profile'], name='universitie_status_cb469f_idx'),
        ),
    ]
