# Generated by Django 5.2.4 on 2026-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_publication_options_publication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='feedback',
            field=models.TextField(blank=True, help_text='Visible to researcher when status = Rejected', verbose_name='Rejection Feedback / Moderator Notes'),
        ),
    ]
