# Generated by Django 5.2.4 on 2025-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0002_upload_delete_innovation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(),
        ),
    ]
