# Generated by Django 5.2.4 on 2025-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0003_alter_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
