# Generated by Django 5.2.4 on 2025-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0004_upload_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='e.g. Prof. Ahmed Mohamed', max_length=200, null=True, verbose_name='Supervisor Name'),
        ),
    ]
