# Generated by Django 5.2.4 on 2025-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0005_upload_supervisor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('thesis', 'Thesis'), ('dissertation', 'Dissertation')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='submission_type',
            field=models.CharField(max_length=100),
        ),
    ]
