# Generated by Django 5.2.4 on 2025-12-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0009_alter_like_created_at_alter_rating_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
