# Generated by Django 5.2.4 on 2025-11-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='orcid',
        ),
    ]
