# Generated by Django 5.2.4 on 2025-12-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_researcherprofile_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='degree',
        ),
    ]
