# Generated by Django 5.2.4 on 2025-12-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_researcherprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='location',
        ),
    ]
