# Generated by Django 5.2.4 on 2025-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_researcherprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
