# Generated by Django 5.2.4 on 2025-12-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_researcherprofile_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
