# Generated by Django 5.2.4 on 2025-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_researcherprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
