# Generated by Django 5.2.4 on 2025-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university_name',
            field=models.CharField(blank=True, help_text='Required if user category is University.', max_length=255, null=True, verbose_name='University Name'),
        ),
    ]
