# Generated by Django 5.2.4 on 2025-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_category',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('university', 'University'), ('conf_organizer', 'Conference Organizer'), ('public_visitor', 'Public Visitor'), ('admin', 'admin')], default='public_visitor', max_length=20),
        ),
    ]
