# Generated by Django 5.2.4 on 2025-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_category',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('university', 'University'), ('conf_organizer', 'Conference Organizer'), ('public_visitor', 'Public Visitor'), ('admin', 'admin'), ('innovator', 'Innovator')], default='public_visitor', max_length=20),
        ),
    ]
